version: '3.3'

services:
  als:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: looking-glass-prod
    restart: always
    network_mode: host
    env_file:
      - .env.prod
    volumes:
      - ./data:/data
      - ./logs:/var/log/als
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    # 生产环境资源限制
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'
