
name: Build and Push Docker Images

on:
  push:
    branches: 
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches: 
      - main
      - master

env:
  REGISTRY: docker.io
  IMAGE_NAME: netmirror

jobs:
  build:
    strategy:
      matrix:
        include:
          - runs-on: [self-hosted, Linux, X64]
            arch: amd64
            platform: linux/amd64
          - runs-on: [self-hosted, Linux, ARM64]
            arch: arm64
            platform: linux/arm64
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Check runner info
        run: |
          echo "Architecture: ${{ matrix.arch }}"
          echo "Platform: ${{ matrix.platform }}"
          uname -a
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=-${{ matrix.arch }}
            type=ref,event=pr,suffix=-${{ matrix.arch }}
            type=semver,pattern={{version}},suffix=-${{ matrix.arch }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.arch }}
            type=semver,pattern={{major}},suffix=-${{ matrix.arch }}
            type=raw,value=latest,enable={{is_default_branch && matrix.arch == 'amd64'}}
            type=raw,value=main-${{ matrix.arch }},enable={{is_default_branch}}
            type=raw,value=latest-${{ matrix.arch }},enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 
